"""
August 1, 2021
Created by: Sebastian Loaiza Correa
"""

SERVER_ADDRESS = "18.208.197.194"
PORT = 8050
BACKLOG = 5
BUFFER_SIZE = 1024
ENCODING_FORMAT = "utf-8"
HELLO = "HELLO"
EXIT = "EXIT"
NEW_BUCKET ="NEW_BUCKET"
LIST_BUCKET = "LIST_BUCKET"
DELETE_BUCKET ="DELETE_BUCKET"
UPLOAD_FILE = "UPLOAD_FILE"
LIST_FILE = "LIST_FILE"
DOWNLOAD_FILE = "DOWNLOAD_FILE"
DELETE_FILE ="DELETE_FILE"

